### PR TITLE
Added Inter Italic font-family files

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description
Google fonts didn't provide Inter's italic font files, but @dbecherdialpad found them on Inter's GH repository. The regular and bold italic files should be added to Dialtone with the proper @font-face declarations.

https://switchcomm.atlassian.net/browse/DT-91?atlOrigin=eyJpIjoiY2E4YmYzYjE4N2JjNDI0MThiYmNhY2YwMzFkNjFiYmUiLCJwIjoiaiJ9

## Pull Request Checklist

 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Provide a description what is being changed, extended, or removed.
 - [x] Link to any issue(s) this request is resolving.
 - [x] Request a review from Drew Chandler, Joshua Hynes, or Ted Goas.

### CODE REVIEW

**Comment by dialpad-drew** [comment]
Hey Julio, shouldn't we see a change to the font-family declaration in the generated CSS? I only see changes being made in Less, but no CSS output in the diff. You should be able to run `npm run start` and the CSS should re-compile.

**Comment by juliodialpad** [comment]
I'm sorry, I didn't added the compiled files to the commit, should I do it?

**Comment by dialpad-drew** [comment]
> I'm sorry, I didn't added the compiled files to the commit, should I do it?

Yea. We don't have any other ~remove~ builds in our CICD, so what we compile locally is what gets published.

**Review by dialpad-drew — APPROVED** [review]

**Comment by dbecherdialpad** [comment]
> Yea. We don't have any other remove builds in our CICD, so what we compile locally is what gets published.

We should really fix this. It's extremely annoying that every single PR that gets merged creates merge conflicts in every other PR. It also junks up the PRs quite a bit.

**Pull request merged**
