### PR TITLE
DT-19 Refactor focus-ring var across form elements

### LINKED ISSUE #316: Refactor focus-ring vars across all form elements
When we updated Dialtone's CSS, we didn't use the global focus-ring vars like we should have. We need to go back and clean that up so focus-rings are declared in a single place.

### PR DESCRIPTION
**Pull request by josedialpad**
## Description
Issue: https://switchcomm.atlassian.net/browse/DT-19
This PR adds `bs-focus-ring` variable in order to use the same `box-shadow` style in all form elements. But only `Input` and `Select` had  the same `box-shadow` value that allowed to replace with the global variable `bs-focus-ring`.

The other components with different `box-shadow` style using `focus-ring` variable are:
- button.less: https://github.com/dialpad/dialtone/blob/version6/lib/build/less/components/button.less#L26 
`box-shadow: 0 0 0 var(--su1) var(--button--bs-color-inner), 0 0 0 calc(var(--su1) + var(--su4)) var(--button--bs-color-outer);`

- link.less: https://github.com/dialpad/dialtone/blob/version6/lib/build/less/components/link.less#L49
`box-shadow: 0px 0px 0px var(--su2) var(--focus-ring);`

- radio-checkbox.less: 
  - https://github.com/dialpad/dialtone/blob/version6/lib/build/less/components/radio-checkbox.less#L60 `.d-checkbox { box-shadow: 0 0 0 var(--su1) var(--white), 0 0 0 var(--su4) var(--check-radio--color-focus);}`
  - https://github.com/dialpad/dialtone/blob/version6/lib/build/less/components/radio-checkbox.less#L211 `.d-radio { box-shadow: 0 0 0 var(--su1) var(--white), inset 0 0 0 var(--su2) var(--white), 0 0 0 var(--su4) var(--check-radio--color-focus); }`

So in these cases the variable `bs-focus-ring` couldn't be used.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [x] Provide a description what is being changed, extended, or removed.
 - [x] Link to any issue(s) this request is resolving.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Drew Chandler, Joshua Hynes, or Ted Goas.

### CODE REVIEW

**Comment by dialpad-drew** [comment]
@josedialpad , why couldn't we use this new var with checkbox and button? With checkbox, it seems to work in inspector; with radio, it doesn't.

If I'm reading the Less correctly, Button appears to generate the same CSS with a different architecture.

**Comment by josedialpad** [comment]
@dialpad-drew they don't have exactly the same `box-shadow` value. I want to be sure we are good unifying these styles with the new variable. Here are the computed properties:

| Component  | Computed `box-shadow` |
| ------------- | ------------- |
| Input  | rgb(255, 255, 255) 0px 0px 0px 1px, rgba(108, 61, 255, 0.75) 0px 0px 0px 4px  |
| Checkbox | rgb(255, 255, 255) 0px 0px 0px 1px, rgba(108, 61, 255, 0.75) 0px 0px 0px 4px |
| Button | rgb(255, 255, 255) 0px 0px 0px 1px, rgba(108, 61, 255, 0.75) 0px 0px 0px 5px |
| Radio | rgb(255, 255, 255) 0px 0px 0px 1px, rgb(255, 255, 255) 0px 0px 0px 2px inset, rgba(108, 61, 255, 0.75) 0px 0px 0px 4px |

With the checkbox you're right, we can replace it with the new variable since it has the same computed value as Input, but with the, Button we have `1px` more of `spread-radius`. Are we ok changing the Button `spread-radius` from 5px to 4px in order to unify styles and use the `focus-ring` variable?

**Comment by dialpad-drew** [comment]
> @dialpad-drew they don't have exactly the same `box-shadow` value. I want to be sure we are good unifying these styles with the new variable. Here are the computed properties:
> 
> Component	Computed `box-shadow`
> Input	rgb(255, 255, 255) 0px 0px 0px 1px, rgba(108, 61, 255, 0.75) 0px 0px 0px 4px
> Checkbox	rgb(255, 255, 255) 0px 0px 0px 1px, rgba(108, 61, 255, 0.75) 0px 0px 0px 4px
> Button	rgb(255, 255, 255) 0px 0px 0px 1px, rgba(108, 61, 255, 0.75) 0px 0px 0px 5px
> Radio	rgb(255, 255, 255) 0px 0px 0px 1px, rgb(255, 255, 255) 0px 0px 0px 2px inset, rgba(108, 61, 255, 0.75) 0px 0px 0px 4px
> With the checkbox you're right, we can replace it with the new variable since it has the same computed value as Input, but with the, Button we have `1px` more of `spread-radius`. Are we ok changing the Button `spread-radius` from 5px to 4px in order to unify styles and use the `focus-ring` variable?

Yes, that's fine for button.

**Comment by josedialpad** [comment]
@dialpad-drew thanks for the answer.
Updated Checkbox and Radio using `focus-ring` variable. https://github.com/dialpad/dialtone/pull/403/commits/622ee0e7ea0f89474a16ff61d180fd712a147416
Updated Button https://github.com/dialpad/dialtone/pull/403/commits/58c84b0bff6ea4ebf759307897c35ab7ce34a68d

**Review by dialpad-drew — APPROVED** [review]

**Review by dbecherdialpad — APPROVED** [review]

**Pull request merged**
