### PR TITLE
feat: add alarm system icon

### PR DESCRIPTION
**Pull request by MengzhenGao**
## Description
Adding alarm logo. Needed for [rewriting post call wrap-up banner](https://switchcomm.atlassian.net/browse/DP-45415) 

Demo:
image

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]
Looks great thanks!

**Comment by MengzhenGao** [comment]
> Looks great thanks!

Thanks Brad! Do you know when the new version will be released? I have a [subtask](https://switchcomm.atlassian.net/browse/DP-46318) to use the new icon

**Comment by braddialpad** [comment]
> Thanks Brad! Do you know when the new version will be released? I have a [subtask](https://switchcomm.atlassian.net/browse/DP-46318) to use the new icon

Yep I can release for you right now.

**Comment by MengzhenGao** [comment]
@braddialpad 

> > Thanks Brad! Do you know when the new version will be released? I have a [subtask](https://switchcomm.atlassian.net/browse/DP-46318) to use the new icon
> 
> Yep I can release for you right now.

Thanks!!

**Pull request merged**
