### PR TITLE
build: add GHA to update dialtone7 after staging PR merge

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description

Added a GHA to cherry-pick commits from last PR into version7 branch.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Comment by braddialpad** [comment]
Hmm, what about things like release commits, we probably don't want to pick those right?

**Comment by braddialpad** [comment]
What if there's a conflict how do we resolve?

**Comment by juliodialpad** [comment]
> Hmm, what about things like release commits, we probably don't want to pick those right?

Idk if there's a way to filter which commits it should pick

**Comment by juliodialpad** [comment]
> What if there's a conflict how do we resolve?

This action will create a PR, we can edit it in case that we need to resolve any conflict

**Review by braddialpad — APPROVED** [review]
Alright, lets do it, see how it works.

**Pull request merged**
