### PR TITLE
Utility classes for positioning and coordinates

### PR DESCRIPTION
**Pull request by tedgoas-dialpad**
The PR creates utility classes for positioning using our existing spacing variables.

This works towards #101

### CODE REVIEW

**Review by dbecherdialpad — APPROVED** [review]
is it possible to not generate the documentation changes until after the PR is ready to merge?

**Comment by hynes-dialpad** [comment]
> is it possible to not generate the documentation changes until after the PR is ready to merge?

@dbecherdialpad Yes, but we'll have to create a new branch. I've been considering this anyway:

 - `develop` is where everything gets merged from various PRs
 - `production` is the new `master` branch

**Comment by tedgoas-dialpad** [comment]
> Update classes to more terse classes

@hynes-dialpad Is this is what we want to do? I'm thinking of the semantic CSS crowd here.

**Comment by hynes-dialpad** [comment]
@TedGoas We've already started with terse classes throughout all the type and display utilities. I'd prefer to keep everything the same.

**Review by hynes-dialpad — APPROVED** [review]

**Pull request merged**
