### PR TITLE
feat: add SVGs for thumbs up and down including update to json file

### PR DESCRIPTION
**Pull request by dialpad-marshall**
## Description
This PR adds `thumb up` and `thumb down` svgs and accompanying updates to the json file.
Tagging @jawreydialpad here

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)
finger-guns

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]

**Comment by josedialpad** [comment]
Merging this PR since it's approved and so we can include in the next release

**Comment by jawreydialpad** [comment]
Hey guys -- sorry to ping y'all on old closed PRs.

Noticed that these thumb icons are being compiled to the wrong file names on `6.7.0`:

Screen Shot 2021-11-22 at 3 18 30 PM

**Comment by braddialpad** [comment]
> Hey guys -- sorry to ping y'all on old closed PRs.
> 
> Noticed that these thumb icons are being compiled to the wrong file names on `6.7.0`:
> 
> Screen Shot 2021-11-22 at 3 18 30 PM

Fixed in 6.8.1

**Comment by jawreydialpad** [comment]
Thank you :)

**Pull request merged**
