### PR TITLE
UC-9657: Add disable self view icons

### PR DESCRIPTION
**Pull request by jimut-dialpad**
## Description
Icons for disable self view.
@amitdialpad Please suggest better names for these icons.

## Pull Request Checklist

 - [ ] Ask the contributors if a similar effort is already in process or has been solved.
 - [ ] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [ ] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)

🙈

### CODE REVIEW

**Comment by dialpad-drew** [comment]
Hey there. A few questions:
* What are these for?
* Can we have better descriptions about the use case(s) these are solving or what contexts are appropriate? The descriptions appear to simply repeat the file name.
* Are these from Material?
* We'll need to make sure these are exported with `#000000` so `gulp svg` properly processed them. Otherwise we won't be able to override their `fill` color. @amitdialpad, are you already working on getting these in the icons Figma library? If so, can you make sure the fill is set accordingly and re-export?

**Comment by jimut-dialpad** [comment]
> What are these for?

For disable self view project.
More info: https://switchcomm.atlassian.net/browse/UC-9657

> Can we have better descriptions about the use case(s) these are solving or what contexts are appropriate? The descriptions appear to simply repeat the file name.

Updated the descriptions as suggested by @amitdialpad.

> Are these from Material?

I am not sure @amitdialpad will be able to answer this.

> We'll need to make sure these are exported with #000000 so gulp svg properly processed them. Otherwise we won't be able to override their fill color. @amitdialpad, are you already working on getting these in the icons Figma library? If so, can you make sure the fill is set accordingly and re-export?

@amitdialpad updated the Figma library.
I had to add  `fill="transparent"` to fix the icons or else they were being shown as solid black icons. 

@dialpad-drew Can you please check the icon files again. Do we need to look into a different way for creating the icons?

**Comment by dialpad-drew** [comment]
@amitdialpad is going to mess with this a bit to make sure our color overrides work as intended. He and I just worked through some of this a bit in Figma.

**Comment by jimut-dialpad** [comment]
Icons have been update as discussed with @amitdialpad

**Review by dialpad-drew — APPROVED** [review]

**Pull request merged**
