### PR TITLE
Add lightbulb icon

### PR DESCRIPTION
**Pull request by tedgoas-dialpad**
Added a lightbulb icon for tips and tricks. I went with the solid version to be consistent with our other icons, even though some designs have been using the outlined version.

Screen Shot 2021-03-08 at 7 57 30 AM

### CODE REVIEW

**Comment by dialpad-drew** [comment]
@TedGoas , can you help me understand the difference between the lightbulb and information icons? Based only on their definitions, I'm not sure it's readily apparent to me.

**Information**
Communicates the ability to learn more about an item. If set inline within a page, usually a tooltip is paired with it to provide clarifying item.

**Lightbulb**
Communicates a tip or trick.

**Comment by tedgoas-dialpad** [comment]
How I understand it:

**Info:** Passive information, if you're interested.
**Tip:** We're suggesting you do something.

**Comment by dialpad-drew** [comment]
> How I understand it:
> 
> **Info:** Passive information, if you're interested.
> **Tip:** We're suggesting you do something.

Gotcha. Do you mind adding that little bit into the description so we can stave off any confusion between the two?

**Review by dialpad-drew — APPROVED** [review]
My only complaint at this point is the lack of GIF. Otherwise, LGTM.

**Comment by tedgoas-dialpad** [comment]
AjarCookedHairstreak-max-1mb

**Pull request merged**
