### PR TITLE
docs(components): reorder examples to the top of the page.

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description

Currently on dialpad.design our components pages do not have the examples on top, most of them start with classes. 
We are making examples appear first on all components pages, classes can come afterwards.

Also renamed current “overview” sections to usage.

Followed the order suggested by @francisrupert.

image

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

### CODE REVIEW

**Comment by francisrupert** [comment]
@juliodialpad,

Very cool, straight-forward reordering goes a long way. While it would be nice to get a "Visual Preview" of the default variant just below the Intro Description, I suppose that should be its own task independent of this one, [DT-458](https://dialpad.atlassian.net/browse/DT-458).

Not immediately seeing a visual only occurs on the few pages that actually have a Usage section, so it's not the worst thing for now.

**Comment by braddialpad** [comment]
> While it would be nice to get a "Visual Preview" of the default variant just below the Intro Description, I suppose that should be its own task independent of this one, [DT-458](https://dialpad.atlassian.net/browse/DT-458).

We should probably do this as part of this change. it does say in the story "Also rename current “overview” sections to usage. This can go after examples."

**Review by braddialpad — CHANGES_REQUESTED** [review]
Move "Usage" after "Examples". Looks good otherwise

**Comment by francisrupert** [comment]
@braddialpad, @juliodialpad 

> We should probably do this as part of this change.

How about like so... 
image

**Comment by braddialpad** [comment]
> How about like so... 

Definitely like the look of this. Where would you put the text that is currently under "examples"? the usage section?

**Comment by juliodialpad** [comment]
> @braddialpad, @juliodialpad
> 
> > We should probably do this as part of this change.
> 
> How about like so... image

Captura de Pantalla 2022-05-24 a la(s) 2 30 42 p m

Definitely looks a lot better, I'll add that "Preview" section there if that's ok

**Comment by francisrupert** [comment]
> Where would you put the text text that is currently under "examples"?

@braddialpad,

I assume you're referring to the text between each example (like screenshot below). If so, we can retain them in current location at least until we consider how (or if) they're moved with any future doc authoring.

image

**Comment by juliodialpad** [comment]
Added preview section to every component and also "usage" section with lorem ipsum to have a better view of what we are expecting.

**Review by braddialpad — APPROVED** [review]
Nice, definitely an improvement. Remember to comment the lorem ipsum before merging, and also get approval from @francisrupert

**Comment by francisrupert** [comment]
@juliodialpad,

Very nice. A few minor nitpicks:

**Remove Preview from Utilities** (or any page without an example to show)

image

**Border Radius on all four sides**

From `d-btr8` to `d-bar8`

image

**Rename "Examples" to "Variants and Examples"**

Encourages "Variants" as part of our shared language. Eventually would like to have a true 1-to-1 mapping to Figma's Variants, and then figure out how Examples plays in the doc site as a complement to Variants.

image

**Comment by francisrupert** [comment]
@juliodialpad Looking good!

**Comment by juliodialpad** [comment]
@francisrupert @braddialpad Want to give a final look before merging? commented the **Usage** sections and lorem ipsum

**Review by francisrupert — APPROVED** [review]
All good!

**Pull request merged**
