### PR TITLE
Add pre-receive hook to enforce commit message convention

### PR DESCRIPTION
**Pull request by josedialpad**
## Description
This PR only add the script in the repo but it needs to be installed in the github enterprise server. More info: https://docs.github.com/en/enterprise-server@3.2/admin/policies/enforcing-policy-with-pre-receive-hooks/managing-pre-receive-hooks-on-the-github-enterprise-server-appliance#creating-pre-receive-hooks

Following PRs will add more info about the commit message convention. For now, a good resource to use is the Conventional Commit specification: https://www.conventionalcommits.org/en/v1.0.0/#summary

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

### CODE REVIEW

**Comment by dbecherdialpad** [comment]
btw @josedialpad we don't have GitHub Enterprise Server (that's the on-prem solution I think?) so I don't know if this will work. cc @jadialpad

**Comment by josedialpad** [comment]
> btw @josedialpad we don't have GitHub Enterprise Server (that's the on-prem solution I think?) so I don't know if this will work. cc @jadialpad

Yes Brad confirmed that we have Github Enterprise but the cloud version, so the alternative solution is a Github Action to validate after the merge, similar to how firespotter reports when the build is broken.

**Comment by braddialpad** [comment]
@josedialpad I think we can close this PR right?

**Comment by josedialpad** [comment]
@braddialpad yes, I'll close it since we can't implement this hook on Github since `pre-receive` hooks are only working on Github Enterprise Server and we're on the Github Enterprise Cloud.

**Pull request closed without merging**
