### PR TITLE
chore: update home page title and description

### PR DESCRIPTION
**Pull request by josedialpad**
## Description
Update home page title and description

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Comment by josedialpad** [comment]
In Slack:
2023-02-14 at 11 59 09

**Review by braddialpad — APPROVED** [review]
Great thanks. @francisrupert are we okay with this description or is there anything you would like to add?

**Comment by francisrupert** [comment]
### Tagline

For now, let's update it to the homepage's current tagline:

> Documented styles, components, and utility classes to help you quickly design and build unified experiences across Dialpad and Dialpad Meetings.

We'll no doubt rewrite it at some point.

### Title

Update the "Dialtone" portion to be "Dialtone Design System". So, for the homepage, the entire string is solely "Dialtone Design System", and carry throughout other pages. e.g. "Components | Dialtone Design System", "Button | Dialtone Design System"

### Image

Use https://dialpad.design/assets/images/home-hero.png (which we'll also ultimately replace).

**Comment by josedialpad** [comment]
@francisrupert thanks for reviewing. Updated title, description and added image for the home page.

2023-02-14 at 18 05 32

**Review by francisrupert — APPROVED** [review]
Thanks! I'm pretty sure we'll redo that image, but good to have it there.

**Pull request merged**
