### PR TITLE
docs: update style for code in dark and light mode

### PR DESCRIPTION
**Pull request by ninamarina**
## Description
Jira ticket: https://dialpad.atlassian.net/browse/DLT-1196
We are changing the approach on how to show code in the documentation, before it was "inverted" comparing to the system theme, now it's using the same one.

In dark mode:
| Before | Now |
|-------|--------|
| image | image |

In light mode:
| Before | Now |
|-------|--------|
| image | image |

We agreed on the new background corresponding to the token `var(--dt-color-surface-moderate)`. But I also had to change the colors for everything inside. I left the same colors that were used before but changed the variable (example: from `blue-300` to `blue-400`), so that when inspecting the different elements the contrast ratio is > 4.5

image

Note to reviewers: Some of the classes are not that easy to check, to please let me know if I missed something

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

## Obligatory GIF (super important!)

themes

### CODE REVIEW

**Comment by francisrupert** [comment]
👀 I like.

**Review by iropolo — APPROVED** [review]
Looks good, it is important design review on this one.
pre-approving it.
Thanks,

**Comment by francisrupert** [comment]
Added @fede-dp as reviewer.

**Review by braddialpad — APPROVED** [review]
Looks great IMO!

**Review by fede-dp — APPROVED** [review]
looks great!

**Pull request merged**
