### PR TITLE
docs: use author name as seed for blog avatar

### PR DESCRIPTION
**Pull request by braddialpad**
## Description
Use the new seed prop in avatar for the blog so each author gets a unique avatar background.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Comment by braddialpad** [comment]
Hmm for some reason this is not working on the preview but works locally..

**Comment by josedialpad** [comment]
> Hmm for some reason this is not working on the preview but works locally..

I think it should be updated to [dialtone-vue 3.33.0](https://github.com/dialpad/dialtone-vue/blob/vue3/CHANGELOG.md#3330-2022-12-24) where the seed avatar was added

**Review by josedialpad — APPROVED** [review]
w/ one comment to update dt-vue version

**Comment by braddialpad** [comment]
> > Hmm for some reason this is not working on the preview but works locally..
> 
> I think it should be updated to [dialtone-vue 3.33.0](https://github.com/dialpad/dialtone-vue/blob/vue3/CHANGELOG.md#3330-2022-12-24) where the seed avatar was added

That was it thanks!

**Pull request merged**
