### PR TITLE
Added Amex, Mastercard, and Visa brand logos.

### PR DESCRIPTION
**Pull request by dialpad-drew**
## Description
Adds Amex, Mastercard, and Visa brand icons per Vicky's request.

## Pull Request Checklist

 - [X] Ask the contributors if a similar effort is already in process or has been solved.
 - [X] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [X] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [X] Ensure all `gulp` scripts successfully compile.
 - [X] Update, remove, or extend all affected documentation.
 - [X] Provide a description what is being changed, extended, or removed.
 - [X] Link to any issue(s) this request is resolving.
 - [X] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [X] Request a review from Drew Chandler, Joshua Hynes, or Ted Goas.

### CODE REVIEW

**Comment by tedgoas-dialpad** [comment]
@andrewdialpad @vcheng-dialpad The solid background makes the AMEX icon look heavier than the rest. Should we invert that one (gray border, white bg, blue logo) to match the others?

**Comment by dialpad-drew** [comment]
> @andrewdialpad @vcheng-dialpad The solid background makes the AMEX icon look heavier than the rest. Should we invert that one (gray border, white bg, blue logo) to match the others?

I'm deferential to @vcheng-dialpad here since this is her feature and I haven't done any of the backing work here to offer an informed opinion. All I'll offer is that it appears Amex's blue background and white foreground is consistent with their brand. Seeing as how this is payments-related, I could see value in accurately presenting the brand as to avoid conscious or subconscious confusion on the user's part.

For my context: is there precedent for us to alter brands' logos or marks for use within our brand icon set?

In case it's helpful, here's how Stripe presents some card logos:
Screen Shot 2021-05-26 at 9 51 01 AM
Screen Shot 2021-05-26 at 9 51 12 AM
Screen Shot 2021-05-26 at 9 51 18 AM
Screen Shot 2021-05-26 at 9 51 27 AM

**Comment by vcheng-dialpad** [comment]
My intention is to consolidate the icons so that the icons is consistent across our platform.

I tried to search for the brand guideline for Amex but was not able to find any specification, so I opted for the credit card styling from Shopify (but open to change it to Stripes styling if thats what we prefer)
image

Personally I didn't take any consideration in terms of the visual styling and alignment with our brand. I assumed that its another companies' brand icon so I didn't want to alter the styling, but I will be glad to update if need be.

**Comment by dialpad-drew** [comment]
> My intention is to consolidate the icons so that the icons is consistent across our platform.
> 
> I tried to search for the brand guideline for Amex but was not able to find any specification, so I opted for the credit card styling from Shopify (but open to change it to Stripes styling if thats what we prefer)
> image
> 
> Personally I didn't take any consideration in terms of the visual styling and alignment with our brand. I assumed that its another companies' brand icon so I didn't want to alter the styling, but I will be glad to update if need be.

My point wasn't that I thought Stripe's was "right," but rather they, like Shopify, show the credit card brands as they are, not as we want them to be.

**Comment by dialpad-drew** [comment]
@TedGoas @vcheng-dialpad I'd like to wrap this today. It's beginning to languish.

**Review by tedgoas-dialpad — APPROVED** [review]
I don't have any strong opposition here, was justing asking the question.

**Pull request merged**
