### PR TITLE
fix(banner): colors

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description

- Updated banner documentation to use dt-banner
- Fixed Banner colors to match designs

image

Default Light
image
image
image
image
image

Important Light
image
image
image
image
image

Default Dark
image
image
image
image
image

Important Dark
image
image
image
image
image

Is that important warning color intended? seems too off for me, but it's using the right token.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Comment by iropolo** [comment]
> Is that important warning color intended? seems too off for me, but it's using the right token.

Ping @fede-dp here

**Review by iropolo — APPROVED** [review]
PR preview didn't work. but I check it out the branch and looks good.
Approving but would be cool to have a design catch here.
Thanks!!

**Review by fede-dp — APPROVED** [review]

**Comment by fede-dp** [comment]
yes! i think the idea is to have contrast with the background so darker in light mode and ligher in dark mode makes sense to me. approved!

**Comment by francisrupert** [comment]
Need to also do the same for `warning+imporant` variants of [Notice](https://dialpad.design/components/notice.html#important) and [Toast](https://dialpad.design/components/toast.html)

**Comment by juliodialpad** [comment]
> PR preview didn't work. but I check it out the branch and looks good. Approving but would be cool to have a design catch here. Thanks!!

Hmm strange, I'll give it a look, seems like we're having old deploy-previews there and now this is not working.

**Comment by juliodialpad** [comment]
> Need to also do the same for `warning+imporant` variants of [Notice](https://dialpad.design/components/notice.html#important) and [Toast](https://dialpad.design/components/toast.html)

All of the use the same base, let me check them and fix in this PR also to avoid more issues on product

**Pull request merged**
