### PR TITLE
Added fixed width to .d-select to fill the available space

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description
With the addition of display: inline-flex to .d-select class, the select inputs are not filling the available width.

https://switchcomm.atlassian.net/browse/DT-100?atlOrigin=eyJpIjoiMjAwZTM0YzM5MTI1NDQzNmJhZTdiNGIyMGY2ZGIyZjMiLCJwIjoiaiJ9

## Pull Request Checklist

 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Provide a description what is being changed, extended, or removed.
 - [x] Link to any issue(s) this request is resolving.

### CODE REVIEW

**Review by dbecherdialpad — COMMENTED** [review]
this matches what we do for `.d-input` etc?

**Comment by ryandialpad** [comment]
> this matches what we do for `.d-input` etc?

I had a look at `input.less` at the `d-input` and `d-textarea` classes and they had `width: 100%` but were missing the webkit fill attribute.

**Comment by juliodialpad** [comment]
should I remove webkit fill from .d-select or create a new PR to add it to other inputs?

**Review by dbecherdialpad — APPROVED** [review]
not 100% what `webkit-fill-available` does but as long as they are both the same 👍🏻

**Pull request merged**
