### PR TITLE
fix: bad syntax in vue files when style tags are used in SVG

### PR DESCRIPTION
**Pull request by braddialpad**
prior to this change if there were style tags within an SVG, when we are building the vue file they would be copied over and embedded within the template. This is erroneous syntax in vue. This change will use regex to extract style tags and then put them at the end of the vue file after the template tags have already been inserted as they should be in a vue SFC.

## Pull Request Checklist

 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.

### CODE REVIEW

**Comment by dbecherdialpad** [comment]
imo allowing styles for SVG elements is a bit dangerous. _Usually_ these generated "class names" are pretty generic and easily clash with other SVGs, eg the play store ones are `.cls-1` etc. Why not just enforce consistency in the SVGs by using inline fills?

**Comment by josedialpad** [comment]
The migration of the classes to the `style` section worked well, though have this error trying to use in `dialtone-vue`:

```
LOG from GenerateFileWebpackPlugin
<i> [GenerateFileWebpackPlugin] [version.txt] [generated]

ERROR in /Users/jose/Code/dialtone/lib/dist/vue/icons/IconPlayStoreBadge.vue?vue&type=style&index=0&lang=css& (./node_modules/css-loader/dist/cjs.js??ref--9-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/dist/cjs.js??ref--9-2!./node_modules/css-loader/dist/cjs.js??ref--14-1!./node_modules/vue-loader/lib??vue-loader-options!/Users/jose/Code/dialtone/lib/dist/vue/icons/IconPlayStoreBadge.vue?vue&type=style&index=0&lang=css&)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

(1:1) /Users/jose/Code/dialtone/lib/dist/vue/icons/IconPlayStoreBadge.vue Unknown word

> 1 | // Imports
    | ^
  2 | var ___CSS_LOADER_API_IMPORT___ = require("../../../../../dialtone-vue/storybook/node_modules/css-loader/dist/runtime/api.js");
  3 | exports = ___CSS_LOADER_API_IMPORT___(true);

 @ /Users/jose/Code/dialtone/lib/dist/vue/icons/IconPlayStoreBadge.vue?vue&type=style&index=0&lang=css&
```

It seems that the CSS Loader in dialtone-vue is not working?

Another thing that noticed is that not all the classes were added when compiling, for instance in the [play-store-badge.svg](https://github.com/dialpad/dialtone/blob/staging/lib/build/svg/brand/play-store-badge.svg) icon, I see:

```
<style>.cls-1{fill:#a6a6a6;}.cls-10,.cls-2,.cls-3{fill:#fff;}.cls-2{stroke:#fff;stroke-miterlimit:10;stroke-width:0.2px;}.cls-4{fill:url(#linear-gradient);}.cls-5{fill:url(#linear-gradient-2);}.cls-6{fill:url(#linear-gradient-3);}.cls-7{fill:url(#linear-gradient-4);}.cls-8{opacity:0.2;}.cls-10,.cls-8,.cls-9{isolation:isolate;}.cls-9{opacity:0.12;}.cls-10{opacity:0.25;}</style>
```

But when building it generates:

```
<style>.cls-2{fill:#fff;stroke:#fff;stroke-miterlimit:10;stroke-width:.2px}.cls-9{isolation:isolate;opacity:.12}</style>
```

That's happening on `staging` too.

**Comment by braddialpad** [comment]
> imo allowing styles for SVG elements is a bit dangerous. _Usually_ these generated "class names" are pretty generic and easily clash with other SVGs, eg the play store ones are `.cls-1` etc. Why not just enforce consistency in the SVGs by using inline fills?

This is a very good point... We should probably not allow these due to high chance of conflict.

**Comment by braddialpad** [comment]
Created PR to inline the generic class names in the play store svg here: https://github.com/dialpad/dialtone/pull/499

I think we can still probably put this PR in. While we should not allow generic generated names I think there is value in allowing proper manually named classes. The class names should use BEM style naming as we do in our apps, which we will have to enforce through review.

**Comment by braddialpad** [comment]
> The migration of the classes to the `style` section worked well, though have this error trying to use in `dialtone-vue`:

hmm seems like a config issue. I'll look into this in a bit

**Comment by josedialpad** [comment]
@dbecherdialpad @braddialpad if the class names used in the icon components might have conflict, can't we use the [scoped styles](https://vue-loader.vuejs.org/guide/scoped-css.html) so each class is specific for each icon component?

**Comment by braddialpad** [comment]
> Another thing that noticed is that not all the classes were added when compiling, for instance in the [play-store-badge.svg]

This actually looks like the minifier correctly doing its work. It inlined all classes that were only a single property, and combined ones that it could.

**Comment by braddialpad** [comment]
> @dbecherdialpad @braddialpad if the class names used in the icon components might have conflict, can't we use the [scoped styles](https://vue-loader.vuejs.org/guide/scoped-css.html) so each class is specific for each icon component?

I think we used to use these in the product at one time but stopped using them across dialpad in place of BEM naming, so I didn't really consider using them. I'm not sure exactly the reason @dbecherdialpad could probably tell you.

**Comment by dbecherdialpad** [comment]
@braddialpad @josedialpad yeah I was gonna mention scoped styles. The reasons we mostly stopped using them in ubervoice were varied but mostly related to how they did (or did not) work with child Vue components. In this case, I think it would actually be totally fine, and is a good use case for scoped styles.

**Comment by braddialpad** [comment]
> It seems that the CSS Loader in dialtone-vue is not working?

Googled around a bunch, think I got the fix for this in https://github.com/dialpad/dialtone-vue/pull/189

Only a storybook issue, the library itself was building fine.

**Comment by braddialpad** [comment]
added scoped to the style tag as requested

**Review by josedialpad — APPROVED** [review]

**Pull request merged**
