### PR TITLE
Tooltip. Adjust tooltip utility class

### PR DESCRIPTION
**Pull request by nikitadialpad**
## Description
Adjust tooltip utility class with positioning styles.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Provide a description what is being changed, extended, or removed.
 - [ ] Link to any issue(s) this request is resolving.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [ ] Request a review from Drew Chandler, Joshua Hynes, or Ted Goas.

### CODE REVIEW

**Comment by dialpad-drew** [comment]
See below screenshots; are the position, wrapping, and z-index changes intentional? They appear like a bug.

Also, why is this necessary?

## Before
Screen Shot 2021-06-04 at 12 33 46 PM

## After
Screen Shot 2021-06-04 at 12 33 34 PM

**Comment by nikitadialpad** [comment]
@dialpad-drew 
somehow missed your last message, apologies for that,
I found that tooltip received styled from button and than gets correct positioning. If button is inline block then tooltip is broken
Screenshot 2021-06-08 at 18 17 46
That's why those styles were added.
Now after refactoring classes the approach is updated as well. So my proposition now would be to add `d-tooltip-container` class for the styles

Update:
pushed the latest changes where I added [css class for parent ](https://github.com/dialpad/dialtone/pull/344/files#diff-ac1bb88ea5a77a0ae9d430dba5a6e27969c6a3c70c1df4a3453094dece4548d8R30). It's needed for Vue component ([board](https://github.com/dialpad/dialtone-vue/issues/19), [PR](https://github.com/dialpad/dialtone-vue/pull/49))

**Comment by dialpad-drew** [comment]
> @dialpad-drew
> somehow missed your last message, apologies for that,
> I found that tooltip received styled from button and than gets correct positioning. If button is inline block then tooltip is broken
> Screenshot 2021-06-08 at 18 17 46
> That's why those styles were added.
> Now after refactoring classes the approach is updated as well. So my proposition now would be to add `d-tooltip-container` class for the styles
> 
> Update:
> pushed the latest changes where I added [css class for parent ](https://github.com/dialpad/dialtone/pull/344/files#diff-ac1bb88ea5a77a0ae9d430dba5a6e27969c6a3c70c1df4a3453094dece4548d8R30). It's needed for Vue component ([board](https://github.com/dialpad/dialtone-vue/issues/19), [PR](https://github.com/dialpad/dialtone-vue/pull/49))

Gotcha. So what's the ideal mark-up for this? The tooltip documentation in this PR is broken, so I can't tell. 😭 Is tooltip still a child of button, or would they be siblings now that there's a common parent container with `position: relative`?

**Comment by nikitadialpad** [comment]
> Gotcha. So what's the ideal mark-up for this? The tooltip documentation in this PR is broken, so I can't tell. 😭 Is tooltip still a child of button, or would they be siblings now that there's a common parent container with `position: relative`?

- The tooltip documentation in this PR is not broken.
- The screen just represents that tooltip position which depends on button styles.
- This behaviour is not so good for vue tooltip component implementation.
- So mine proposition is: move the styles to another abstract entity.
- We don't push styles to dialtone-vue, so what do you think what is the good solution for this case?
- [added comment for clarification](https://github.com/dialpad/dialtone-vue/pull/49/files#r648605418)

**Review by dialpad-drew — APPROVED** [review]

**Pull request merged**
