### PR TITLE
docs: fix styling issues.

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description

With the update of VuePress, we had styling issues due to VuePress recently added a div wrapper to the main content, and that changed our CSS overriding rules.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Comment by braddialpad** [comment]
Hmm seeing a couple issues still, padding of "use for / don't use for" looks off compared to before. @francisrupert Do I recall you made some changes to the class table as well?

**Comment by francisrupert** [comment]
Yeah, there's quite a bit still wrong—at least from what I see at this moment at https://dialpad.design/deploy-previews/pr-614/components/button.html

This has to be mostly about the selectors in `overrides.less` needed to be highly specific to get it themed, particularly within `.theme-default-content:not(.custom) {...}` Probably more than just an extra `<div>`.

* Sidebar nav is wholly unaffected by the `overrides`, retaining VuePress' [dark sidebar nav](https://user-images.githubusercontent.com/1165933/173583310-9225b773-45b3-4e13-928b-5232679bccfa.png)
* [Green links](https://user-images.githubusercontent.com/1165933/173583129-9c6173c5-36bb-4781-9060-5186f40f95eb.png)
* Spacing of prose content is off, including in _Use / Don't use_.
* [Tables dark borders](https://user-images.githubusercontent.com/1165933/173583436-599ebacc-0662-4f6a-9409-85c69ac74d94.png)

image

**Comment by juliodialpad** [comment]
> Yeah, there's quite a bit still wrong—at least from what I see at this moment at https://dialpad.design/deploy-previews/pr-614/components/button.html
> 
> This has to be mostly about the selectors in `overrides.less` needed to be highly specific to get it themed, particularly within `.theme-default-content:not(.custom) {...}` Probably more than just an extra `<div>`.
> 
> * Sidebar nav is wholly unaffected by the `overrides`, retaining VuePress' [dark sidebar nav](https://user-images.githubusercontent.com/1165933/173583310-9225b773-45b3-4e13-928b-5232679bccfa.png)
> * [Green links](https://user-images.githubusercontent.com/1165933/173583129-9c6173c5-36bb-4781-9060-5186f40f95eb.png)
> * Spacing of prose content is off, including in _Use / Don't use_.
> * [Tables dark borders](https://user-images.githubusercontent.com/1165933/173583436-599ebacc-0662-4f6a-9409-85c69ac74d94.png)
> 
> image

How much spacing should have every `h2` and `h3` header titles?

**Comment by braddialpad** [comment]
Definitely looking much better, something wrong with notice though. One of the overrides messing with it?

Screen Shot 2022-06-14 at 1 12 27 PM

**Comment by juliodialpad** [comment]
> Definitely looking much better, something wrong with notice though. One of the overrides messing with it?
> 
> Screen Shot 2022-06-14 at 1 12 27 PM

Definitely VuePress added a bunch of new styling, but found a way to easily remove them, good catch, Thanks!

**Review by braddialpad — APPROVED** [review]
This looks good to me now. I say we merge and deploy ASAP so we don't have a broken site, but I'd still like a designer's eye on this so let's make sure @francisrupert has a look later. (I believe he's stuck in meetings all day).

**Comment by juliodialpad** [comment]
> This looks good to me now. I say we merge and deploy ASAP so we don't have a broken site, but I'd still like a designer's eye on this so let's make sure @francisrupert has a look later. (I believe he's stuck in meetings all day).

Sure! It's better to have a site with minor issues to fix that a completely broken site, I'll merge now and will fix later any comment that @francisrupert could have.

**Pull request merged**
