### PR TITLE
feat: convert root-layout to full css grid

### PR DESCRIPTION
**Pull request by braddialpad**
## Description
Related to other PR in dialtone vue https://github.com/dialpad/dialtone-vue/pull/1253. This is the implementation on the dialtone side. Root layout converted to use pure CSS grid and get rid of the grid / flexbox hybrid we had previously. This should also fix the remaining issues on the docsite with root layout. 

Fairly big change so please check for any weird edge cases you can think of.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Comment by juliodialpad** [comment]
The TOC area is broken while resizing the screen

Screenshot 2023-10-17 at 12 12 30 p m

But seems like on dialpad.design is broken too, maybe just missing the correct grid-area?

**Review by juliodialpad — APPROVED** [review]
Aside from the broken TOC area, everything looks good, thanks!

**Comment by braddialpad** [comment]
> The TOC area is broken while resizing the screen
> 
> Screenshot 2023-10-17 at 12 12 30 p m
> But seems like on dialpad.design is broken too, maybe just missing the correct grid-area?

Oh, that has actually been broken forever haha, not 100% sure what the best solution is here, should the TOC move to the top like it does in mobile mode?

**Comment by braddialpad** [comment]
merging as this was a preexisting issue. however we should look at it.

**Pull request merged**
