### PR TITLE
chore: update dialtone-vue

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description

Updated dialtone-vue to latest to update avatar examples.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Review by iropolo — APPROVED** [review]
Thanks, there were a reason on why we didnt have `^` previously?

**Comment by braddialpad** [comment]
> Thanks, there were a reason on why we didnt have `^` previously?

actually yeah good point. we changed to use exact versions recently.

@juliodialpad instead of using `npm install @dialpad/dialtone-vue@vue3` use `npm install @dialpad/dialtone-vue@vue3 --save-exact`

**Review by braddialpad — CHANGES_REQUESTED** [review]
see comment

**Comment by iropolo** [comment]
> > Thanks, there were a reason on why we didnt have `^` previously?
> 
> actually yeah good point. we changed to use exact versions recently.
> 
> @juliodialpad instead of using `npm install @dialpad/dialtone-vue@vue3` use `npm install @dialpad/dialtone-vue@vue3 --save-exact`

Could we add a comment to point this out? something like

`"@dialpad/dialtone-vue": "^3.82.1", // exact version only`

**Comment by juliodialpad** [comment]
> > Thanks, there were a reason on why we didnt have `^` previously?
> 
> actually yeah good point. we changed to use exact versions recently.
> 
> @juliodialpad instead of using `npm install @dialpad/dialtone-vue@vue3` use `npm install @dialpad/dialtone-vue@vue3 --save-exact`

Forgot about that, updated to use exact version

**Review by braddialpad — APPROVED** [review]

**Pull request merged**
