### PR TITLE
Adding app store play store images

### PR DESCRIPTION
**Pull request by cvvikashdialpad**
## Description
Added app store bade and play store badge SVG to the dialtone icon

## Pull Request Checklist

 - [ ] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)
Screenshot 2021-10-25 at 3 47 08 PM

### CODE REVIEW

**Comment by dialpad-drew** [comment]
@amitdialpad can we get these in the icon library?

@cvvikashdialpad where did you source these?

**Comment by dialpad-drew** [comment]
Resolves #487

**Comment by amitdialpad** [comment]
@dialpad-drew 
1. Download on the appstore badges - Downloaded the white & dark lock up from the Marketing resources website. 
https://developer.apple.com/app-store/marketing/guidelines/
2. Get it on Google Play badge - Downloaded the EPS from the Google Play badge page 
https://play.google.com/intl/en_us/badges/

Two variations of the Appstore badge & the Playstore badge is in the Figma file. 
1. App / Download / Appstore Badge / English Black Lockup
2. App / Download / Appstore Badge / English White Lockup
3. App / Download / GooglePlay Badge / English Lockup

I'll help @cvvikashdialpad with these SVGs so he can raise the PR again.

**Comment by dialpad-drew** [comment]
@amitdialpad it sounds like you're going to see if the one App Store asset works for both light and dark mode before we decide whether to include both in this PR?

**Review by dialpad-drew — APPROVED** [review]
Looks like y'all decided you only needed the dark Apple app store brand icon.

**Pull request merged**
