### PR TITLE
Add new arrow right icon

### PR DESCRIPTION
**Pull request by linlidialpad**
# Pull Request Process

> First, congrats on opening an pull request. We appreciate the help!
> 
> Second, use the following template to make sure your pull request is reviewed and merged in a timely fashion.

## Before submitting a pull request

 - [x] Have you asked the contributors if a similar effort is already in process or has been solved?
 - [x] You've reviewed the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md)?
 
## Checklist for completing a pull request

To ensure your pull request is approved, please make sure the following items are completed: 

 - [x] Your pull request uses `staging` as its base branch. (All PRs using `production` as its base branch will be declined).
 - [x] All `gulp` scripts successfully compile.
 - [x] Any affected documentation has been updated, removed, or extended.
 - [x] Provide a description what is being changed, extended, or removed.
 - [x] Link to any issue(s) this request is resolving.
 - [x] Request a review from Joshua Hynes, Ted Goas, or David Becher.

### Description
Issue: https://github.com/dialpad/dialtone/issues/125

In the new integration setting project, we have a feature to make a panel expand and collapse, so we would like to add a new right arrow icon to be used to together with the existing IconArrowDropDown. 

The design and svg file is from Polly Lee. See following screenshot. 

Screen Shot 2020-10-05 at 10 45 16 AM

### CODE REVIEW

**Review by tedgoas-dialpad — APPROVED** [review]
LGTM, thanks!

@hynes-dialpad @linlidialpad  should we add `arrow-left.svg` while we're in here? So we have all four directions?

**Comment by hynes-dialpad** [comment]
@linlidialpad Can you provide a screenshot/comp of where this icon will be used?

**Comment by linlidialpad** [comment]
@tedgoas-dialpad @hynes-dialpad Here's the screenshot. It's supposed to be used as a section expander in this design. Adding left arrow is okay for me, but I'm not sure what the usage would be. 

94968239-6bda6a80-04b5-11eb-9630-8cc847f48464

**Comment by linlidialpad** [comment]
Hey @hynes-dialpad @tedgoas-dialpad, haven't heard update from you regarding the left-arrow icon yet, if you don't have preference on that, are you okay that I just merge this PR first (since I have a feature implementation currently waiting for the right arrow)? I can add the left arrow later.

**Comment by tedgoas-dialpad** [comment]
@linlidialpad I'm ok with that, I've already approved this PR. You ok with that @hynes-dialpad ?

**Review by hynes-dialpad — APPROVED** [review]

**Pull request merged**
