### PR TITLE
Fix selected and disabled button states

### PR DESCRIPTION
**Pull request by hynes-dialpad**
This PR removes the various `--selected` and `--disabled` button classes previously in Dialtone. Previously the pseudo state and an alternate class was provided, but in most instances the class instance is not needed. In order to have these classes required the button less code to be overly complicated. This simplifies the button code and ensures button styles are applied correctly.

This fixes #42 and #20.

### CODE REVIEW

**Comment by vincentdialpad** [comment]
This would be a breaking change for anywhere using the classes exclusively. I believe there was a request to allow the disabled class to be applied separately by @mraj to still trigger events.

**Comment by hynes-dialpad** [comment]
@vincentdialpad yeah I saw that in the earlier requests. I just pushed a change to add those classes back in as well as loading button classes as well. I don't think we need the `.d-btn--selected` classes.

**Review by vincentdialpad — APPROVED** [review]
I guess an argument for requiring a base d-btn class is it would make maintaining these different states easier.

**Comment by hynes-dialpad** [comment]
@vincentdialpad Yeah, it would, but we've moved this direction so specific states could be applied while applying one class. I guess we could always re-visit it in the future. Maybe when we create a Vue button component? ¯\\_(ツ)_/¯

**Pull request merged**
