### PR TITLE
docs: add less/css linter to Dialtone. update contributing.md doc

### PR DESCRIPTION
**Pull request by nikitadialpad**
## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF
giphy -  - 2021-11-15 17-53-23

### CODE REVIEW

**Comment by braddialpad** [comment]
Hey Nick, are we not linting on commit here via lint-staged? Seems like we are in dt-vue can we do the same here?

**Comment by nikitadialpad** [comment]
> Hey Nick, are we not linting on commit here via lint-staged? Seems like we are in dt-vue can we do the same here?

hey Brad, we're linting on [commit with husky](https://github.com/dialpad/dialtone/blob/staging/.husky/pre-commit).

**Comment by braddialpad** [comment]
> > Hey Nick, are we not linting on commit here via lint-staged? Seems like we are in dt-vue can we do the same here?
> 
> hey Brad, we're linting on [commit with husky](https://github.com/dialpad/dialtone/blob/staging/.husky/pre-commit).

ahh yeah thanks, didn't see the hook in the package.json so I thought it wasn't active.

Let's mention in the doc how it will be automatically linted on commit

**Comment by nikitadialpad** [comment]
> Let's mention in the doc how it will be automatically linted on commit

sure, added

**Review by braddialpad — APPROVED** [review]
thanks!

**Pull request merged**
