### PR TITLE
feat(avatar): changed from gradient bg to variety of flat colors

### PR DESCRIPTION
**Pull request by francisrupert**
## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

image

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]
I see no problems here but since this is a breaking change let's NOT merge this yet until we do the updates on the dialtone-vue side.

**Comment by francisrupert** [comment]
Of course. I'll add some pre-grooming details to [DT-1175](https://dialpad.atlassian.net/browse/DT-1175) and whoever takes that one can coordinate the timing of that with merging and releasing this PR.

[DT-1175]: https://dialpad.atlassian.net/browse/DT-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

And I'll leave [DT-1174](https://dialpad.atlassian.net/browse/DT-1174) and [DT-1177](https://dialpad.atlassian.net/browse/DT-1177) as in `Code Review`.

[DT-1174]: https://dialpad.atlassian.net/browse/DT-1174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1177]: https://dialpad.atlassian.net/browse/DT-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by francisrupert** [comment]
@braddialpad 

Add some presumptive grooming details on [DT-1175](https://dialpad.atlassian.net/browse/DT-1175).

[DT-1175]: https://dialpad.atlassian.net/browse/DT-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by braddialpad** [comment]
Dialtone Vue PR is ready. Merging and releasing.

**Pull request merged**
