### PR TITLE
docs: fix spacing issues

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description
Fixed spacing issues with `page-toc` and a bug with `sticky header` that we haven't detected 

https://user-images.githubusercontent.com/87546543/210884184-8b0e4e93-b1f8-46dc-9803-263bb3bd6884.mov

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Comment by francisrupert** [comment]
@juliodialpad,

Good catch on the scrolling sticky positioning bug, I'd been bothered by that.

This is definitely a strong improvement to resolve the TOC awkward positioning. One thing I'd love to see is a uniform layout between the pages. There's currently some undesirable shifting of the main content as you jump from page to page (see attached screencast). 

The way you have it set up to subtract the TOC width doesn't play well with pages that don't have a TOC. 

So this is effectively two things different things...

1. Perhaps we need a custom "landing" layout for Design, Components, and Guides. 
2. For the main layout, how can we avoid that awkward shift when no TOC exists?

https://user-images.githubusercontent.com/1165933/210899162-c153be35-6f1b-4bff-a5c8-5e4a0af5c318.mov

**Comment by francisrupert** [comment]
@juliodialpad, `staging` now all the doc site tweaks I mentioned this morning. Hopefully merging in `staging` to this branch and resolving won't be too much of a headache.

**Comment by juliodialpad** [comment]
@francisrupert this is fixed, please review it again.

**Review by francisrupert — APPROVED** [review]
@juliodialpad, 

Looks like the staging merge wasn't too much to overcome. This is leaps-and-bounds better than the awkward shifting of before. 

Approved with one tiny nitpick change: reduce the gap between the article content and TOC.

image

**Pull request merged**
