### PR TITLE
docs(new-theme): footer

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description

This PR includes the footer functionality:

- Page - Last updated
- Previous and Next page link: this is automatically calculated, there's no need to add `prev` or `next` to the frontmatter.

This does not include the #755 fixes, so leave page content styling apart in this PR. just focus on footer functionality, look and style.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).

### CODE REVIEW

**Review by braddialpad — COMMENTED** [review]
Hmm I'm not seeing any prev / next buttons at the bottom of the pages on the preview.

**Comment by juliodialpad** [comment]
> Hmm I'm not seeing any prev / next buttons at the bottom of the pages on the preview.

Sorry for not including a preview in the PR, those are the buttons at the bottom of the page that take you to the previous or next section on the page. The titles are not "previous" or "next".

Screenshot 2022-12-02 at 5 10 58 p m

**Comment by braddialpad** [comment]
> Sorry for not including a preview in the PR, those are the buttons at the bottom of the page that take you to the previous or next section on the page. The titles are not "previous" or "next".

Ah it was actually there on the first page I looked at (components landing page) but I didn't notice it because the styles were messed up and it was so far to the right lol. But yeah looks like it's working well.

**Review by braddialpad — APPROVED** [review]
Looks good by me.

**Pull request merged**
