### PR TITLE
feat(device settings): gear icon for device settings

### PR DESCRIPTION
**Pull request by Mansidialpad**
## Description
Provide a description of what this pull request is adding, updating, extending, or removing. If this request is addressing an issue, please link to that issue.
https://switchcomm.atlassian.net/browse/UC-13029

## Pull Request Checklist

 - [ ] Ask the contributors if a similar effort is already in process or has been solved.
 - [ ] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [ ] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [ ] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [ ] Request a review from Brad Paugh, David Becher, or Drew Chandler.

### CODE REVIEW

**Review by braddialpad — COMMENTED** [review]
Isn't this pretty much identical to the settings icon we already have? (settings.svg)

**Comment by Mansidialpad** [comment]
> Isn't this pretty much identical to the settings icon we already have? (settings.svg)

The current settings icon has extra white space, which makes it look smaller than other icons of similar size.
image

Here is Amit's comment on the ticket: https://switchcomm.atlassian.net/browse/UC-13029?focusedCommentId=468956

**Comment by dialpad-drew** [comment]
The way I read that ticket, it seems like @amitdialpad was suggesting we fix the existing icon, not add a new one. Maybe I misunderstood though.

**Comment by braddialpad** [comment]
Got ya, let's just replace the current system icon with the corrected one rather than making a new.

**Comment by Mansidialpad** [comment]
> Got ya, let's just replace the current system icon with the corrected one rather than making a new.

We also want to use this icon for device settings only. Currently, IconSettings is being used for user's settings for which we are going to have a new svg. Amit is working it. I believe that we should replace IconSettings with that. Let me know what you think.

**Comment by braddialpad** [comment]
> We also want to use this icon for device settings only. Currently, IconSettings is being used for user's settings for which we are going to have a new svg. Amit is working it. I believe that we should replace IconSettings with that. Let me know what you think.

Ah I see, yeah I think this is okay then.

**Review by braddialpad — APPROVED** [review]

**Pull request merged**
