### PR TITLE
feat: add a few social icons for contact center

### PR DESCRIPTION
**Pull request by tedgoas-dialpad**
Adding icons for DialogFlow, Apple, WhatsApp, Instagram, and Messenger.

### CODE REVIEW

**Review by braddialpad — COMMENTED** [review]
If you look closely, the whatsapp icon seems to not have a fully transparent background, was this intended?

Screen Shot 2022-02-03 at 2 34 18 PM

**Comment by tedgoas-dialpad** [comment]
That's intended since it's what Facebook has in its official brand center, though I can be talked into removing it if it'd make for a better Dialpad UI.

**Comment by braddialpad** [comment]
> That's intended since it's what Facebook has in its official brand center, though I can be talked into removing it if it'd make for a better Dialpad UI.

I don't have the answer to this so we can leave it the way it is for now. Easy enough to change later if needed.

**Review by braddialpad — APPROVED** [review]
Looks good! Just fix the commit message by adding `feat:` in front of it

**Comment by tedgoas-dialpad** [comment]
@braddialpad Looks like one of the checks is failing, are you able to help sort this out and merge?

**Comment by braddialpad** [comment]
yeah I got you

**Pull request merged**
