### PR TITLE
docs: add "Make a request" button in homepage

### PR DESCRIPTION
**Pull request by josedialpad**
## Description

Added “Make a request” button links to Monday form.

## Pull Request Checklist

 - [ ] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

## Obligatory GIF (super important!)
monday

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]

**Comment by josedialpad** [comment]
@dialpad-drew we are okay merging this?

**Review by dialpad-drew — APPROVED** [review]
@josedialpad yes, with one request/questions! Thanks for your patience on this!

On tall screens, there can be a white strip at the bottom if the page. I'm not exactly sure what a good solution for making this more fluid. Any ideas?
Screen Shot 2022-01-12 at 6 12 01 PM

**Comment by josedialpad** [comment]
> On tall screens, there can be a white strip at the bottom if the page. I'm not exactly sure what a good solution for making this more fluid. Any ideas? Screen Shot 2022-01-12 at 6 12 01 PM

@dialpad-drew hey Drew, I'm not sure I can reproduce this on my computer, can you please give details about the browser used and an idea about the dimensions of the window or screen? I need to ask just in case, don't you have the zoom of the page changed?

**Comment by braddialpad** [comment]
> @josedialpad yes, with one request/questions! Thanks for your patience on this!
> 
> On tall screens, there can be a white strip at the bottom if the page. I'm not exactly sure what a good solution for making this more fluid. Any ideas?

I'm not so sure this is really a problem. I have one portrait oriented monitor and this is how it looks:
Screen Shot 2022-01-14 at 9 14 32 AM

If the height of the purple bar stretched all the way to the bottom of the page instead, I don't think it would look good.

**Comment by dialpad-drew** [comment]
Got it. I can live with it for the moment.

**Pull request merged**
