### PR TITLE
chore: update commitlint report message

### PR DESCRIPTION
**Pull request by josedialpad**
Jira ticket: https://switchcomm.atlassian.net/browse/DT-292

## Description
Commitlint doesn't provide an easy way to customize report message so added messages giving the basic format and an example to give a bit more of information about the commit message convention. Also updated the Get help url where the full documentation can be read.

Example in PR with single commit:

```
Since your PR has a single commit, this commit should adhere to the commit message convention.
correct format: <type>(<scope>): <subject>
example: feat: add modal component
Please amend your commit message (git commit --amend) if commitlint reports an error and push using: git push --force-with-lease
⧗   input: add txt
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/dialpad/dialtone-vue/blob/staging/.github/COMMIT_CONVENTION.md

Error: Process completed with exit code 1.
```

[Example](https://github.com/dialpad/dialtone/runs/4401117058?check_suite_focus=true) with error in the PR's title:

```
The PR's title should adhere to the commit message convention.
correct format: <type>(<scope>): <subject>
example: feat: add modal component
⧗   input: add txt
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/dialpad/dialtone-vue/blob/staging/.github/COMMIT_CONVENTION.md

Error: Process completed with exit code 1.
```

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [ ] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]
Should work well enough I think, Do we have a way of customizing the actual rules at all? Some of the rules are pretty strict (no period at end of message for example)

**Comment by josedialpad** [comment]
> Should work well enough I think, Do we have a way of customizing the actual rules at all? Some of the rules are pretty strict (no period at end of message for example)

yeah the rules are customizable easily but not the error messages

**Comment by braddialpad** [comment]
Nice is there somewhere I can see the list of default rules?

**Comment by josedialpad** [comment]
> Nice is there somewhere I can see the list of default rules?

here are the ones we're using:
https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#rules

Maybe we need to add the link to the rules in our `COMMIT_CONVENTION` doc since it has good examples there.

**Comment by josedialpad** [comment]
Added the link to the rules in our `COMMIT_CONVENTION` doc https://github.com/dialpad/dialtone/pull/515/commits/43db187429910ba2403176a70f73ed860a035b55

**Comment by braddialpad** [comment]
Yeah definitely add the link there.

I propose these changes to the rules:

subject-full-stop - disable, this is just annoying
body-max-line-length - disable, I can see why to limit the commit message but limiting the body makes no sense to me.
header-max-length - make this 72 as that is the point where it gets cut off in github.

**Comment by josedialpad** [comment]
the rules were updated and also in dt-vue https://github.com/dialpad/dialtone-vue/pull/206

**Pull request merged**
