### PR TITLE
feat(emoji-picker, datepicker): revert style migration from dialtone8

### PR DESCRIPTION
**Pull request by iropolo**
## Description

Reverted styles from dialtone8 of emoji-picker and datepicker componets.

### CODE REVIEW

**Comment by iropolo** [comment]
working on linter fixes

**Comment by iropolo** [comment]
linter fixed

**Review by braddialpad — APPROVED** [review]
thanks!

**Comment by braddialpad** [comment]
Merging this cuz alex needs it for demo tomorrow.

**Pull request merged**
