### PR TITLE
feat(docsite): merge vuepress migration into staging

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description

We need to merge the VuePress migration branch into staging, this contains all the changes necessary to merge it.

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [x] Update, remove, or extend all affected documentation.
 - [x] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

### CODE REVIEW

**Review by braddialpad — APPROVED** [review]

**Comment by braddialpad** [comment]
Definitely not reviewing this whole thing, you can just let er rip

**Comment by juliodialpad** [comment]
I'm unauthorized to merge to staging, can you give me permissions please @braddialpad 

Captura de Pantalla 2022-05-12 a la(s) 11 52 44 a m

**Comment by braddialpad** [comment]
uhh what?? this must have got messed up in the reorg.. let me look

**Comment by braddialpad** [comment]
Alright you should have admin permission again.

**Comment by juliodialpad** [comment]
> Alright you should have admin permission again.

Thanks! It's working again

**Pull request merged**
