### PR TITLE
feat(button): add active styles

### PR DESCRIPTION
**Pull request by juliodialpad**
## Description

Added Active button styles pseudo-class.

**Ticket**: https://dialpad.atlassian.net/browse/DT-308?atlOrigin=eyJpIjoiZmY1NDQ3MDZjYjAyNGZhZTliYzFkMzJlNjM5NDkyMzEiLCJwIjoiaiJ9

**Figma File**: https://www.figma.com/file/zP2uyVxAg4notGNZwW64mW/branch/XnnI2V4nrwhZWmxRM70sMm/Components?node-id=2055%3A4256

## Pull Request Checklist

 - [x] Ask the contributors if a similar effort is already in process or has been solved.
 - [x] Review the [contribution guidelines](https://github.com/dialpad/dialtone/blob/staging/.github/CONTRIBUTING.md).
 - [x] Use `staging` as your pull request's base branch. (All PRs using `production` as its base branch will be declined).
 - [x] Ensure all `gulp` scripts successfully compile.
 - [ ] Update, remove, or extend all affected documentation.
 - [ ] Ensure no private Dialpad links or info are in the code or pull request description (Dialtone is a public repo!).
 - [x] Request a review from Brad Paugh, David Becher, or Drew Chandler.

### CODE REVIEW

**Review by braddialpad — CHANGES_REQUESTED** [review]
We need to update documentation for this right?

**Comment by juliodialpad** [comment]
> We need to update documentation for this right?

Where should I add the documentation? I haven't found any documentation on :active button styling either in Dialtone 5 or 6

**Comment by braddialpad** [comment]
> > We need to update documentation for this right?
> 
> Where should I add the documentation? I haven't found any documentation on :active button styling either in Dialtone 5 or 6

Yeah I guess we don't need to, it's completely internal to the button, for example we don't say anything about hover button styles either.

**Review by braddialpad — APPROVED** [review]

**Comment by juliodialpad** [comment]
> > > We need to update documentation for this right?
> > 
> > 
> > Where should I add the documentation? I haven't found any documentation on :active button styling either in Dialtone 5 or 6
> 
> Yeah I guess we don't need to, it's completely internal to the button, for example we don't say anything about hover button styles either.

Yeah, that's what I was thinking too.

I just realized I need to add and `.d-btn--active` class so we can retain the active state in dialtone-vue, I'll create a new PR for that changes.

**Pull request merged**
